### ISSUE TITLE
Build Version Without Microphone Permission Required To Avoid Triggering MacOS In-Use Dot

### ISSUE THREAD

**Issue by Ciscog33k** [kyleneideck/BackgroundMusic#726] opened 2024-03-17 20:58 UTC
Hello,

Can you please release a version of BackgroundMusic without any explicit requirements for the MacOS Mic permission?  Or at the very least make it so when the permission is denied, that the app can continue to function for users who with to not grant that access as persistent use of the permission renders the MacOS in-use monitoring system useless.

Thanks!

**Comment by kyleneideck** [comment] 2024-04-26 07:03
I'm closing this as a duplicate of #562, but I've actually been working on this recently. It's a much larger change than you would think. Not sure when it'll be ready. See https://github.com/kyleneideck/BackgroundMusic/issues/562#issuecomment-986609439 if you're interested in the details.

**Closed by kyleneideck** 2024-04-26 07:03 UTC
