### ISSUE TITLE
Unable to update to the latest version, also unable to reinstall

### ISSUE THREAD

**Issue by nonozone** [kyleneideck/BackgroundMusic#738] opened 2024-05-05 07:43 UTC
`==> Upgrading background-music
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/c565567888f78645dd0e6890063a31b822b92335/Casks/
################################################################################################################# 100.0%
==> Downloading https://github.com/kyleneideck/BackgroundMusic/releases/download/v0.4.3/BackgroundMusic-0.4.3.pkg
Already downloaded: /Users/nono/Library/Caches/Homebrew/downloads/f26261d677adedfa65aaf9099670dfbb0a883dfa3b6a01e3ceb1a9859659e34f--BackgroundMusic-0.4.3.pkg
==> Removing launchctl service com.bearisdriving.BGM.XPCHelper
Password:
==> Uninstalling packages with sudo; the password may be necessary:
com.bearisdriving.BGM
==> Removing files:
/Library/Application Support/Background Music
/Library/Audio/Plug-Ins/HAL/Background Music Device.driver
/usr/local/libexec/BGMXPCHelper.xpc
Could not kickstart service "com.apple.audio.coreaudiod": 1: Operation not permitted
==> Purging files for version 0.4.3 of Cask background-music
Error: background-music: Failure while executing; `/usr/bin/sudo -E -- /bin/launchctl kickstart -kp system/com.apple.audio.coreaudiod` exited with 1. Here's the output:
Could not kickstart service "com.apple.audio.coreaudiod": 1: Operation not permitted`

`❯ brew install --cask background-music
==> Upgrading 1 outdated package:
background-music 0.4.0 -> 0.4.3
==> Upgrading background-music
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/c565567888f78645dd0e6890063a31b822b92335/Casks/
Already downloaded: /Users/nono/Library/Caches/Homebrew/downloads/fd2f53a7ba1d35e16aa0480fb6040686f741d62caf9fae90e99193f41b9a18d1--background-music.rb
==> Downloading https://github.com/kyleneideck/BackgroundMusic/releases/download/v0.4.3/BackgroundMusic-0.4.3.pkg
Already downloaded: /Users/nono/Library/Caches/Homebrew/downloads/f26261d677adedfa65aaf9099670dfbb0a883dfa3b6a01e3ceb1a9859659e34f--BackgroundMusic-0.4.3.pkg
==> Removing launchctl service com.bearisdriving.BGM.XPCHelper
Password:
==> Uninstalling packages with sudo; the password may be necessary:
==> Removing files:
/Library/Application Support/Background Music
/Library/Audio/Plug-Ins/HAL/Background Music Device.driver
/usr/local/libexec/BGMXPCHelper.xpc
Could not kickstart service "com.apple.audio.coreaudiod": 1: Operation not permitted
==> Purging files for version 0.4.3 of Cask background-music
Error: background-music: Failure while executing; `/usr/bin/sudo -E -- /bin/launchctl kickstart -kp system/com.apple.audio.coreaudiod` exited with 1. Here's the output:
Could not kickstart service "com.apple.audio.coreaudiod": 1: Operation not permitted`

**Comment by kyleneideck** [comment] 2024-05-06 06:12
I'm pretty sure this is a duplicate of #727. There's a workaround in the comments of that issue.

If you want to get the issue fixed properly, you'd have to raise an issue in the Homebrew repo.

**Closed by kyleneideck** 2024-05-06 06:12 UTC
Labels: bug

**Comment by nonozone** [comment] 2024-05-08 23:54
Yes, thank you, that worked!
