### ISSUE TITLE
Cant control Microsoft Teams volume

### ISSUE THREAD

**Issue by RodrigoGCoelhoo** [kyleneideck/BackgroundMusic#282] opened 2020-04-16 19:38 UTC
Hey guys, new to the app. I don't know if im missing something, but I can't control Microsoft Teams audio using BackgroundMusic

**Comment by iiasceri** [comment] 2020-04-17 13:51
I see whatchu doin here :3

**Comment by iiasceri** [comment] 2020-04-17 13:52
https://staticz.com/soundcontrol/

**Comment by kristofk** [comment] 2020-04-21 08:52
Microsoft Teams app controls the notification sounds etc. and creates another thread for meetings called "Microsoft Teams Helper." You need to control this thread in the More Apps dropdown menu, marked as red below.
<img width="540" alt="Screen Shot 2020-03-27 at 3 33 09 PM" src="https://user-images.githubusercontent.com/24462323/77756575-80d6cc80-7040-11ea-96b7-33cc4ae8daf6.png">

_Originally posted by @anaxilaus in https://github.com/kyleneideck/BackgroundMusic/issues/268#issuecomment-604977210_

**Comment by phot0n** [comment] 2020-04-29 08:31
@kristofk Thanks for that ...but I tried to do the same but it didn't work :(

**Comment by kyleneideck** [comment] 2020-04-29 09:20
@phot0n Restarting is worth a try. Also, #268 has a bit more info. Does any of that help?

**Comment by phot0n** [comment] 2020-04-30 06:57
@kyleneideck thanks for such quick reply :)
As it turns out that teams was not routing the audio through background-music. Doing that fixed the issue for me.
Thanks again :)

**Comment by ovidio** [comment] 2020-05-07 15:58
@kyleneideck thanks for your reply. I was pulling my hair trying to figure out why Teams was not working with this. Turns out, like you said, I need to go into Teams and use Background-Music as the input/output

**Comment by krapgras** [comment] 2020-06-12 13:14
Can be closed as its duplicate of #268 and seems to be resolved using the helper?

**Comment by kyleneideck** [comment] 2020-06-13 06:17
I think we should still fix it so you can use the main slider instead of the helper ones, but yeah it looks like a duplicate to me, too. Closing, thanks.

**Closed by kyleneideck** 2020-06-13 06:17 UTC
