### ISSUE TITLE
AirPods Support

### ISSUE THREAD

**Issue by lbenicio** [kyleneideck/BackgroundMusic#318] opened 2020-06-14 14:08 UTC
Hey folks,

On my MacBook Pro 13 on macOS 10.15.5, when using BackgroundMusic with internal speakers it works great, but when I connect my AirPods it does not work.

If I went to settings and change the sound output back to BackgroundMusic (after connecting the AirPods) the sound on the AirPods became just noise, unrecognizable. Like someone mini-punching the microphones on their other side with their fingers.

Sorry for the not-so-precise bug report...

**Comment by lbenicio** [comment] 2020-06-14 17:45
Doing some tests I discovered that this happens when the output source is set to background music but the input source is set to AirPods. if I set both of then to background music, no sound is captured by neither built-in nor AirPods microphone.

**Comment by kyleneideck** [comment] 2020-06-15 01:57
Thanks for the info, but is this a duplicate of #186? Or maybe #272?

It looks like so far the only workaround is setting the AirPods back to their 2-channel mode in Audio MIDI Setup if they swap to their 1-channel mode.

**Closed** 2023-09-06 20:34 UTC
