### ISSUE TITLE
Fails on El Capitan 10.11.3 (15D21)

### ISSUE THREAD

**Issue by gunnard** [kyleneideck/BackgroundMusic#15] opened 2016-04-18 15:02 UTC
The application cannot be opened because its executable is missing.
ERROR: Install script failed at line 207. This is probably a bug in the script. Feel free to report it.

**Comment by krapgras** [comment] 2020-06-12 13:08
Duplicate of #16

**Closed** 2020-06-13 07:00 UTC
