### ISSUE TITLE
Build fails on 10.9

### ISSUE THREAD

**Issue by jdidion** [kyleneideck/BackgroundMusic#41] opened 2016-04-23 12:43 UTC
[build_and_install.log.zip](https://github.com/kyleneideck/BackgroundMusic/files/232950/build_and_install.log.zip)

**Comment by kyleneideck** [comment] 2016-04-23 15:14
I think the errors in your log file are all caused by nullability attributes (`__nonnull`/`__nullable`) that your version of Clang doesn't support. I'm downloading Xcode 6.2 to see if I can debug this locally, but I have pretty slow internet so in the meantime I created a [10.9 support branch](https://github.com/kyleneideck/BackgroundMusic/tree/10.9Support) that should fix those errors. (It just defines the attributes to the empty string if the compiler doesn't support them.) I suspect you'd just get a new bunch of errors if you build that branch now, so it might now be worth bothering yet. I'll update this issue after I've tried with Xcode 6.2.

**Comment by kyleneideck** [comment] 2016-04-27 22:43
I've updated the 10.9Support branch and I think it should compile and run on 10.9 with Xcode 6 now. Though I might have missed some runtime bugs since I only have a 10.11 machine to test on. 

It doesn't seem to cause any problems with the 10.11 build, so hopefully I can merge it as soon as I'm able to test it on 10.9/10.10.

I'm gonna close this as a dupe of #39 for now, even though I'm not completely sure that it is. Feel free to reopen it if you disagree. Thanks for the report.

**Closed by kyleneideck** 2016-04-27 22:43 UTC
