### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by KevinTyrrell** [kyleneideck/BackgroundMusic#114] opened 2017-05-12 16:55 UTC
Please put a compiled release version on your repo. Only extremely advanced users know how to compile code with Xcode.

**Comment by kyleneideck** [comment] 2017-05-14 02:25
You're probably already aware of this, but releasing binaries built on a developer's computer would be less secure than releasing ones built on Travis CI, since their VMs are much less likely to be compromised. (Ideally, though, the builds would be [reproducible](https://reproducible-builds.org/).) It would also make automating the process a lot easier.

@sscotth has done some work on this: https://github.com/sscotth/BackgroundMusic. See his [.travis.yml](https://github.com/sscotth/BackgroundMusic/blob/travis-release/.travis.yml) and the discussion on #12.

Having his .travis.yml also include `Background Music Device.driver` and `BGMXPCHelper.xpc` in the zipfile, along with `Background Music.app`, would be enough for a minimal binary release. I'm planning to try that after I finish the issue I'm working on now, if someone else doesn't do it before then.

Installing those binaries would be pretty complicated, though, (see my comment in #12) so we'll want to write an automated installer after that, possibly a .pkg.

**Comment by KevinTyrrell** [comment] 2017-05-14 02:45
You're saying compiling a program into a runnable file on your own computer then distributing that file online is dangerous? How can that be? The only information inside of that binary file is from the source code of your program. They can decompile it and look at your code, yes, but nothing else is there that can harm you.

**Comment by kyleneideck** [comment] 2017-05-14 04:07
I agree it would be very unlikely for Xcode to accidentally compile sensitive information into the binaries, but if someone got access to my computer they'd be able to modify the binaries before I distributed them. Then everyone who ran those binaries would also be running whatever the attacker added.

I would think my computer is much more likely to be compromised than the Travis server would be, since people generally use their personal computers to run a much wider variety of software than servers do. Travis' servers do run its users' code, but only in virtual machines and I'm pretty sure [VM escapes](https://en.wikipedia.org/wiki/Virtual_machine_escape) are much less common than [RCEs](https://en.wikipedia.org/wiki/Arbitrary_code_execution). (I actually found one myself recently, in software I use regularly: http://seclists.org/fulldisclosure/2017/Mar/6.)

Of course, someone with access to my computer could insert malicious source code into one of my commits instead, but we would at least have a chance of someone else reading the code and finding it. Or I could read the code again using a different computer.

All that said, Travis' servers would be very high-value targets and it's not great to have a single point of failure for so many projects, so I think reproducible builds would probably be worth investigating.

**Comment by kyleneideck** [comment] 2017-06-21 02:45
I've committed a script that builds a .pkg installer and released v0.1.1 (see the README). The releases are built and deployed on Travis thanks to @sscotth, so unless I missed anything I this one is resolved. Thanks for reporting it.

**Closed by kyleneideck** 2017-06-21 02:45 UTC

**Comment by KevinTyrrell** [comment] 2017-06-21 17:48
Good to hear. I'm still not sure about the compiled release security thing as I've never heard of that before but I understand for being wary. If you're really worried you could always boot up a VM, compile your release there, and then upload it to GitHub and there will be absolutely no personal data associated. Anyways, appreciate the follow up .
