### ISSUE TITLE
exclude apps

### ISSUE THREAD

**Issue by adrian-cmd** [kyleneideck/BackgroundMusic#34] opened 2016-04-20 09:42 UTC
is it possible to exclude some apps via the preferences?

I've the following problem:
the mail app makes a noise after sending an email, facebook chat makes noises, ... and all of them are pausing spotify.

**Comment by kyleneideck** [comment] 2016-04-22 15:54
Not yet, but I'm planning to add it.

I'm closing this as a duplicate of #5. (But feel free to reopen if you think I'm wrong about that. Actually, I'm not sure whether GitHub lets you do that. If not, just leave a comment and I'll reopen it.) 

I've posted a workaround on #5 that you might want to try. It's a bit unfortunate I can't merge the two issues rather than closing one, because this one has some additional information that could be useful. Anyway, thanks for reporting it.

**Closed by kyleneideck** 2016-04-22 15:54 UTC
